

name: Test user-related scripts

on:
  push:
    branches: [ actions ]
  pull_request:
    paths: 
      - "setup/users/**"
      - ".github/workflows/users-tests.yaml"

  workflow_dispatch:

jobs:
  
  tests:
    
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Create /shared
        run: sudo mkdir /shared

      - name: Test add_new_user.bash
        run: | 
          echo "abc" | sudo bash $GITHUB_WORKSPACE/setup/users/add_new_user.bash testuser
          id testuser
          grep testuser /shared/.userslist
          sudo grep "abc" /shared/home/testuser/.ssh/authorized_keys
      
      - name: Test remove_user.bash
        run: |
          echo "Y" | sudo bash $GITHUB_WORKSPACE/setup/users/remove_user.bash testuser
          if id testuser &>/dev/null ; then
            exit 1
          fi
          if grep testuser /shared/.userslist &>/dev/null ; then
            exit 1
          fi
          sudo ls -1qA /shared/home/.backup/testuser/ | grep -q . 